# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ollama.fullname" . }}-config
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
data:
  https_proxy: {{ .Values.global.https_proxy | quote }}
  http_proxy: {{ .Values.global.http_proxy | quote }}
  no_proxy: {{ .Values.global.no_proxy | quote }}
  LLM_MODEL_ID: {{ .Values.LLM_MODEL_ID | quote }}
