# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

DATAPREP_BACKEND: "OPENSEARCH"
OPENSEARCH_HOST: "opensearch-cluster-master"
OPENSEARCH_PORT: 9200
OPENSEARCH_INITIAL_ADMIN_PASSWORD: ""
OPENSEARCH_SSL: false
INDEX_NAME: "rag-opensearch"
KEY_INDEX_NAME: "file-keys"
TIMEOUT_SECONDS: 600
SEARCH_BATCH_SIZE: 10

tei:
  enabled: true
redis-vector-db:
  enabled: false
milvus:
  enabled: false
opensearch:
  enabled: true
  persistence:
    enabled: false
  singleNode: true
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: "" # must match value above or data-prep cannot access Opensearch
